// app/[locale]/layout.tsx

import './globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'
import localFont from "next/font/local"
import Footer from '@/src/components/Footer/Footer'
import Header from '@/src/components/Header/header'

type Props = {
  children: ReactNode
  params: { locale: string }
}
// Define the ES first font
const firstFontES = localFont({
  src: '../../../public/fonts/Helvetica.ttf',
  variable: "--font-firstES",
  fallback: ["'roboto'", "'open sans'", "'sans-serif'"],
});

// Define the ES second font
const secondFontES = localFont({
  src: '../../../public/fonts/Helvetica-light.ttf',
  variable: '--font-secondES',
  fallback: ["'roboto'", "'open sans'", "sans-serif"],
});

// Define the AR first font
const firstFontAR = localFont({
  src: '../../../public/fonts/ArbFONTS-Bold.ttf',
  variable: "--font-firstAR",
  fallback: ["'roboto'", "'open sans'", "'sans-serif'"],
});

// Define the AR second font
const secondFontAR = localFont({
  src: '../../../public/fonts/ArbFONTS-Light.ttf',
  variable: '--font-secondAR',
  fallback: ["'roboto'", "'open sans'", "sans-serif"],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

//function to get the translations
async function getMessages(locale: string) {
  try {
    return (await import(`../../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }
}

//function to generate the routes for all the locales
export async function generateStaticParams() {
  return ['en', 'ar'].map((locale) => ({ locale }))
}



export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  const messages = await getMessages(locale)
  const isRTL = locale === 'ar'; // Check if the locale is 'fr'
  return (
    <html lang={locale}>
      <body dir={`${isRTL ? 'rtl' : ''}`}   className={`${firstFontAR.variable} ${secondFontAR.variable}  ${firstFontES.variable} ${secondFontES.variable} text-black text-lg min-h-screen overflow-x-hidden`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {/* <Header  /> */}
          {children}
          {/* <Footer locale={locale} /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
